"""empty message

Revision ID: 0638db4179d6
Revises: 14d4309ad03c
Create Date: 2025-09-29 12:43:21.314005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0638db4179d6'
down_revision: Union[str, None] = '14d4309ad03c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mnist', sa.Column('label', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mnist', 'label')
    # ### end Alembic commands ###
