"""empty message

Revision ID: 076f5df62305
Revises: 9d0d1aa1b93f
Create Date: 2025-09-29 13:20:04.504353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076f5df62305'
down_revision: Union[str, None] = '9d0d1aa1b93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urban',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urban')
    # ### end Alembic commands ###
