"""empty message

Revision ID: 13f84e58d930
Revises: 3c29f2718335
Create Date: 2025-09-29 13:01:26.728105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f84e58d930'
down_revision: Union[str, None] = '3c29f2718335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('speech_commands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speech_commands')
    # ### end Alembic commands ###
