"""empty message

Revision ID: 9d0d1aa1b93f
Revises: 13f84e58d930
Create Date: 2025-09-29 13:13:55.669227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0d1aa1b93f'
down_revision: Union[str, None] = '13f84e58d930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtzan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audio', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gtzan')
    # ### end Alembic commands ###
